# Generated by Django 4.1.4 on 2023-03-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('celular', models.CharField(blank=True, max_length=33, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('enfermidades', models.CharField(blank=True, max_length=255, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=255, null=True)),
                ('lesao', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivo_curto', models.CharField(max_length=255)),
                ('objetivo_longo', models.CharField(max_length=255)),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='alunos/foto_frente')),
                ('foto_lado', models.ImageField(blank=True, null=True, upload_to='alunos/foto_lado')),
                ('foto_verso', models.ImageField(blank=True, null=True, upload_to='alunos/foto_verso')),
                ('avaliacao_fisica', models.ImageField(blank=True, null=True, upload_to='alunos/avaliacao_fisica')),
                ('exame_sangue', models.ImageField(blank=True, null=True, upload_to='alunos/exame_sangue')),
                ('pago', models.BooleanField(default=False)),
                ('cadastrado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dieta', models.PositiveSmallIntegerField(choices=[(1, 'Totalmente'), (2, 'Regularmente'), (3, 'Não Segui')])),
                ('dificuldade_dieta', models.TextField(blank=True, null=True)),
                ('suplemento', models.PositiveSmallIntegerField(choices=[(1, 'Totalmente'), (2, 'Regularmente'), (3, 'Não Segui')])),
                ('dificuldade_suplemento', models.TextField(blank=True, null=True)),
                ('treino', models.PositiveSmallIntegerField(choices=[(1, 'Totalmente'), (2, 'Regularmente'), (3, 'Não Segui')])),
                ('dificuldade_treino', models.TextField(blank=True, null=True)),
                ('aerobico', models.PositiveSmallIntegerField(choices=[(1, 'Totalmente'), (2, 'Regularmente'), (3, 'Não Segui')])),
                ('dificuldade_aerobico', models.TextField(blank=True, null=True)),
                ('melhorou', models.TextField(blank=True, null=True)),
                ('pode_melhorar', models.TextField(blank=True, null=True)),
                ('foto_frente', models.ImageField(upload_to='alunos/foto_frente')),
                ('foto_lado', models.ImageField(upload_to='alunos/foto_lado')),
                ('foto_verso', models.ImageField(upload_to='alunos/foto_verso')),
                ('video', models.CharField(max_length=255)),
                ('comprometimento', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('avalia_coach', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('sugestoes', models.TextField(blank=True, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('aluno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno', to='accounts.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.FileField(blank=True, null=True, upload_to='protocolos')),
                ('peso_comentario', models.CharField(max_length=255)),
                ('dieta_comentario', models.TextField(blank=True, null=True)),
                ('dificuldade_dieta', models.TextField()),
                ('suplemento_comentario', models.TextField()),
                ('treino_comentario', models.TextField()),
                ('aerobico_comentario', models.TextField()),
                ('melhorias_comentario', models.TextField()),
                ('fotos_comentario', models.TextField(max_length=255)),
                ('video', models.TextField(blank=True, max_length=255, null=True)),
                ('objetivos_comentario', models.TextField(blank=True, max_length=255, null=True)),
                ('sugestoes_comentario', models.TextField(blank=True, null=True)),
                ('comentarios_finais', models.TextField(blank=True, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('feedback', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='accounts.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=None, max_length=33, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('conquistas', models.TextField(blank=True, null=True)),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='coach/foto_perfil')),
                ('foto_certificado', models.ImageField(blank=True, null=True, upload_to='coach/certificado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_coach', to='accounts.coach'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
