# Generated by Django 4.1.4 on 2023-03-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='protocolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolo_feedback', to='accounts.protocolo'),
        ),
        migrations.AlterField(
            model_name='retorno',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retorno_protocolo', to='accounts.feedback'),
        ),
    ]
