# Generated by Django 4.1.4 on 2023-03-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.FileField(blank=True, null=True, upload_to='protocolos')),
                ('aluno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_protocolo', to='accounts.aluno')),
            ],
        ),
    ]
