# Generated by Django 4.1.4 on 2023-03-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback_protocolo_alter_retorno_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replica',
            name='retorno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retorno', to='accounts.retorno'),
        ),
        migrations.AlterField(
            model_name='retorno',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retorno_protocolo', to='accounts.protocolo'),
        ),
    ]
