# Generated by Django 3.2.18 on 2023-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_replica_retorno_alter_retorno_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='peso_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
