# Generated by Django 3.2.18 on 2023-03-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230330_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='objetivo_curto',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='objetivo_longo',
            field=models.CharField(max_length=155),
        ),
    ]
