# Generated by Django 3.2.18 on 2023-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_replica_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='kcal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
