# Generated by Django 3.2.18 on 2023-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_retorno_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='avaliacao_fisica',
            field=models.FileField(blank=True, null=True, upload_to='alunos/avaliacao_fisica'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='exame_sangue',
            field=models.FileField(blank=True, null=True, upload_to='alunos/exame_sangue'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='avaliacao_fisica',
            field=models.FileField(blank=True, null=True, upload_to='alunos/avaliacao_fisica'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='exame_sangue',
            field=models.FileField(blank=True, null=True, upload_to='alunos/exame_sangue'),
        ),
        migrations.AlterField(
            model_name='retorno',
            name='fotos_comentario',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='retorno',
            name='peso_comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
