# Generated by Django 3.2.18 on 2023-06-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_aluno_peso_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='avatar',
            field=models.ImageField(blank=True, max_length=333, null=True, upload_to='coach/foto_perfil'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='foto_certificado',
            field=models.ImageField(blank=True, max_length=333, null=True, upload_to='coach/certificado'),
        ),
    ]
